# Generated by Django 4.1.2 on 2023-08-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='handle',
        ),
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
